name: Java Build

on:
  push:
    branches: [ main, task-3 ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.0.16'

      - name: Run Spotless Apply
        run: ./gradlew :spotlessApply

      - name: Build with Gradle
        run: ./gradlew clean build