name: Shellcheck Pipeline

on:
  push:
    branches: [ '**' ]
  schedule:
    - cron: '0 13 * * *'
#    - cron: '0 0 * * 4'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck

      - name: Run ShellCheck
        run: |
          shellcheck pre_deploy.sh
          if [ $? -eq 0 ]; then
            echo "ShellCheck completed successfully"
          fi